version: '3'
services:
  frontend:
    container_name: frontend
    build: ./
    ports:
      - '3000:3000'
    command: yarn start
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
